# Kunci Print Guard Configuration (.env style)
# Modify default values here before compiling

PRINT_GUARD_ADMIN_PIN=1011
PRINT_GUARD_EPSON_IP=192.168.8.225
PRINT_GUARD_EPSON_PORT=9100
PRINT_GUARD_LOCAL_PROXY_PORT=9100
PRINT_GUARD_WEB_PORT=9101
